### ISSUE TITLE
ListServices panics with "reflect: slice index out of range"

### ISSUE THREAD

**Issue by UnsungHero97** [OpsLevel/opslevel-go#155]
I think there might be a bug with the latest `v2023.1.21` release, though it might be an issue with `go-graphql-client`, not quite sure yet. The issue is that calling `ListServices()` ...

```
import "github.com/opslevel/opslevel-go/v2023"
...
client := opslevel.NewGQLClient(opslevel.SetAPIToken(token))
services, err := client.ListServices()
if err != nil {
  return err
}
```

... panics with this error ...

```
panic: reflect: slice index out of range

goroutine 49 [running]:
reflect.Value.Index({0x104f37040?, 0x140000380f0?, 0x0?}, 0x104f37040?)
        /opt/homebrew/Cellar/go/1.20.1/libexec/src/reflect/value.go:1414 +0x17c
github.com/hasura/go-graphql-client/pkg/jsonutil.(*decoder).decode(0x14000a498a8)
        /path/to/project/vendor/github.com/hasura/go-graphql-client/pkg/jsonutil/graphql.go:168 +0x1788
github.com/hasura/go-graphql-client/pkg/jsonutil.(*decoder).Decode(0x14000a498a8, {0x104f2fda0?, 0x140000380f0?})
        /path/to/project/vendor/github.com/hasura/go-graphql-client/pkg/jsonutil/graphql.go:78 +0x1a8
github.com/hasura/go-graphql-client/pkg/jsonutil.UnmarshalGraphQL({0x14000be8000, 0x2001f, 0x22000}, {0x104f2fda0, 0x140000380f0})
        /path/to/project/vendor/github.com/hasura/go-graphql-client/pkg/jsonutil/graphql.go:24 +0xfc
github.com/hasura/go-graphql-client.(*Client).processResponse(0x140003a4090, {0x104f2fda0?, 0x140000380f0?}, {0x14000be8000?, 0x104f2fda0?, 0x140000380f0?}, 0x140004ada98?, {0x10502cb80, 0x0}, {0x0, ...})
        /path/to/project/vendor/github.com/hasura/go-graphql-client/graphql.go:269 +0x70
github.com/hasura/go-graphql-client.(*Client).do(0x140008be7f0?, {0x1050314e8?, 0x14000112000?}, 0xec?, {0x104f2fda0, 0x140000380f0}, 0x14000274ab8?, {0x0?, 0x140004ada01?, 0x14000274a20?})
        /path/to/project/vendor/github.com/hasura/go-graphql-client/graphql.go:247 +0x68
github.com/hasura/go-graphql-client.(*Client).Query(...)
        /path/to/project/vendor/github.com/hasura/go-graphql-client/graphql.go:52
github.com/opslevel/opslevel-go/v2023.(*Client).QueryCTX(...)
        /path/to/project/vendor/github.com/opslevel/opslevel-go/v2023/clientGQL.go:91
github.com/opslevel/opslevel-go/v2023.(*Client).Query(0x104f83ca0?, {0x104f2fda0?, 0x140000380f0?}, 0x5?)
        /path/to/project/vendor/github.com/opslevel/opslevel-go/v2023/clientGQL.go:87 +0x58
github.com/opslevel/opslevel-go/v2023.(*ServiceConnection).Hydrate(0x140003980a0, 0x140003a0030)
        /path/to/project/vendor/github.com/opslevel/opslevel-go/v2023/service.go:264 +0x180
github.com/opslevel/opslevel-go/v2023.(*ServiceConnection).Query(0x140003980a0, 0x140003a40f0?, {0x104f2fda0?, 0x140003980a0?}, 0x31692b80cbf82f8?)
        /path/to/project/vendor/github.com/opslevel/opslevel-go/v2023/service.go:246 +0x4c
github.com/opslevel/opslevel-go/v2023.(*Client).ListServices(0x140003a0030)
        /path/to/project/vendor/github.com/opslevel/opslevel-go/v2023/service.go:284 +0x104
```

However, this seems to only be happening when importing `v2023`. The following works as expected ...

```
import "github.com/opslevel/opslevel-go"
...
client := opslevel.NewClient(token)
services, err := client.ListServices()
if err != nil {
  return err
}
```

**Comment by rocktavious** [comment]
Hey @UnsungHero97 - Since version https://github.com/OpsLevel/opslevel-go/releases/tag/v2023.3.14 we have refactored all `List*` methods and ensured they are properly tested.  You should not have this problem if you upgrade to that version.

Let us know and If i don't hear back from you in a few weeks i'll close this out.  Thanks.
